runtime: python311  # Or your preferred version
entrypoint: gunicorn -b :$PORT server:app  # Replace `main` with your main Python file (without .py)
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1